### ISSUE TITLE
demo command broken: undefined argument

### ISSUE THREAD

**Issue by ptensschi** [antmicro/renode-run#4]
Running the demo leads to following issue:

```
renode-run demo -b stm32f072b_disco hello_world
Traceback (most recent call last):
  File "~/.venv/bin/renode-run", line 8, in <module>
    sys.exit(main())
  File "~/.venv/lib/python3.10/site-packages/renode_run/__main__.py", line 352, in main
    ({
  File "~/.venv/lib/python3.10/site-packages/renode_run/__main__.py", line 288, in demo_command
    ret = subprocess.run([renode_path, temp.name] + renode_arguments)
NameError: name 'renode_arguments' is not defined. Did you mean: 'renode_args'?
```

**Comment by mateusz-holenko** [comment]
Thanks for reporting the issue. The proposed fix is now merged to `main`.
